### ISSUE TITLE
API endpoint for getting a random proverb

### ISSUE THREAD

**Issue by andela-joyebanji** [lagos-devs/hiddenwisdom-api#25]
A user might what to make a request for a random proverb from the bot side. e.g `get me a proverb in english`. The bot team needs an endpoint that it consume to fetch a random proverb in the supported languages

**Comment by andela-ooranagwa** [comment]
@andela-joyebanji thanks for pointing this out. We'll be updating the proposed search feature to accept robust querying.

**Comment by andela-ooranagwa** [comment]
I will be closing this in favour of #14. Let's continue the discussions there.
