### ISSUE TITLE
Proverb Translations

### ISSUE THREAD

**Issue by sofiengwin** [lagos-devs/hiddenwisdom-api#37]
The current implementation of translations uses _self join_ association. We want to separate translations to a different table. The JSON data coming from the front-end will look like this.

{"proverb":{
  "body": "Proverb body",
  "langunage": "english",
  "tags": ["widom", "life", "opportunity"],
  "translations": [
    {"body": "Yoruba proverb", "langunage": "yoruba" },
    {"body": "Igbo proverb", "language": "igbo" }
  ]
}}

Create a new translation for each translation in the translations array.

**Comment by betkom** [comment]
@andela-gogbara Is this the same as what I'm working on? cos it lacks a description

**Comment by sofiengwin** [comment]
@andela-tkomolafe Yes, this is the story. Sorry for not adding a description earlier.

**Comment by sofiengwin** [comment]
Fixed by https://github.com/FBDevCLagos/hiddenwisdom-api/pull/44
